name: ig_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.7+5
  intl: ^0.17.0-nullsafety.1
  provider: ^6.0.5
  uuid: ^3.0.7
  firebase_storage: ^11.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
